# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: MusicBot

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn package --file pom.xml

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Get time
        uses: gerred/actions/current-time
        id: time 
      - uses: actions/create-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.time.outputs.time }}
          release_name: v0.2.7 - {{ steps.time.outputs.time }}
          body: Auto-Release from Commit
          draft: true
          prerelease: false  
            
